# Generated by Django 3.2.13 on 2022-08-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data/hora'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data/hora'),
        ),
    ]
