# Generated by Django 4.1 on 2022-08-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_data_alteracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data/hora'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data/hora'),
        ),
    ]
