# Generated by Django 4.1 on 2022-08-31 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contato_data_alteracao_and_more'),
        ('tarefas', '0005_alter_tarefa_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='contato_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='contatos.contato'),
            preserve_default=False,
        ),
    ]
