# Generated by Django 4.1 on 2022-08-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220831_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data/hora'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_cadastro',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data/hora'),
        ),
    ]
