# Generated by Django 4.1 on 2022-08-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('data_alteracao', models.DateTimeField(verbose_name='data/hora')),
                ('data_cadastro', models.DateTimeField(blank=True, null=True, verbose_name='data/hora')),
            ],
        ),
    ]
